PycharmProjects/tea_timer/tea/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'tea'

urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^add/$', views.create_tea, name='tea-add'),

    url(r'^(?P<pk>[0-9]+)/update/$', views.TeaUpdate.as_view(), name='tea-update'),

    url(r'^(?P<pk>[0-9]+)/delete/$', views.TeaDelete.as_view(), name='tea-delete'),

    # url(r'^(?P<tea_id>[0-9]+)/brew/(?P<pk>[0-9]+)/update/$', views.GongFuBrewUpdate.as_view(), name='gfbrew-update'),

    # url(r'^brew/(?P<pk>[0-9]+)/delete/$', views.GongFuBrewDelete.as_view(), name='gfbrew-delete'),

    url(r'^(?P<tea_id>[0-9]+)/add_brew/$', views.create_gfbrew, name='gfbrew-add'),

    url(r'^brew/(?P<pk>[0-9]+)/update/$', views.update_gfbrew, name='gfbrew-update'),

    url(r'^brew/(?P<brew_id>[0-9]+)/delete/$', views.delete_gfbrew, name='gfbrew-delete'),

    url(r'^brew/(?P<brew_id>[0-9]+)/timer/$', views.steep_gfbrew, name='gfbrew-steep'),


    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),

]

PycharmProjects/tea_timer/tea/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Tea(models.Model):
    user = models.ForeignKey(User, default=12)
    name = models.CharField(max_length=250)
    type = models.CharField(max_length=250)
    price = models.FloatField()
    rating = models.IntegerField()
    picture = models.FileField()
    origin = models.CharField(max_length=250)
    tasting_notes = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('tea:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' - ' + self.type


class WesternBrew(models.Model):
    tea = models.ForeignKey(Tea, on_delete=models.CASCADE)
    brew_name = models.CharField(max_length=100)
    water_qty = models.FloatField()
    temp_C = models.IntegerField()
    tea_qty = models.FloatField()
    min_brew_time = models.FloatField()
    max_brew_time = models.FloatField()

    def __str__(self):
        return self.tea.name + " " + self.brew_name + ' Western ' + str(self.pk)


class GongFuBrew(models.Model):
    tea = models.ForeignKey(Tea, on_delete=models.CASCADE)
    brew_name = models.CharField(max_length=100)
    gaiwan_size = models.FloatField()
    temp_C = models.IntegerField()
    tea_qty = models.FloatField()
    steep_num = models.IntegerField()
    steep_times_string = models.CharField(max_length=100)
    steep_times = ArrayField(models.IntegerField())

    def get_absolute_url(self):
        return reverse('tea:gfbrew-update', kwargs={'pk': self.pk})

    def __str__(self):
        return self.tea.name + " " + self.brew_name + " Gong Fu " + str(self.pk)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=254, blank=False)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

PycharmProjects/tea_timer/tea/templates/tea/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Tea Tiles{% endblock %}</title>
    <!--Loads the path to the static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'tea/app.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'tea/style.css' %}"/>﻿

</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'tea:index' %}">TeaSir</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'tea:index' %}">
                            <span class="glyphicon glyphicon-leaf" aria-hidden="true" ></span> {{ user.first_name }}'s Teas
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'tea:tea-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true" ></span>&nbsp; Add Tea
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="">
                            <a href="{% url 'logout' %}">
                               <span class="glyphicon glyphicon-log-out" aria-hidden="true" ></span>&nbsp; Logout {{ user.username }}
                            </a>
                        </li>
                    {% else %}
                        <li class="">
                            <a href="{% url 'login' %}">
                                <span class="glyphicon glyphicon-log-in" aria-hidden="true" ></span>&nbsp; Login
                            </a>
                        </li>
                    {% endif %}

                </ul>

            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}


</body>
</html>

PycharmProjects/tea_timer/tea/templates/tea/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TeaSir{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'tea/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'tea/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'tea:index' %}">TeaSir</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'tea:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'login' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

PycharmProjects/tea_timer/tea/templates/tea/details.html
{% extends 'tea/base.html' %}
{% block title %}{{ tea }}{% endblock %}
{% block teas_active %}active{% endblock %}

{% block body %}

<!-- Left Tea Info -->
    <div class="col-sm-4 col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="{% url 'tea:detail' tea.id %}">
                    {% if tea.picture.url %}
                        <img src="{{ tea.picture.url }}" class="img-responsive">
                    {% else %}
                        <h3>No image to display</h3>
                    {% endif %}
                </a>
                <h1>{{ tea.name }}</h1>
                <h2><strong>{{ tea.type }}</strong></h2>
                <h3>${{ tea.price }}</h3>
                <!-- Put the rest of the info in here for the tea when you get the chance -->
                <h4>Rating: {{ tea.rating }}</h4>
                <h4>Origin: {{ tea.origin }}</h4>
                <p>Notes: {{ tea.tasting_notes }}</p>

                <div class="caption">
                    <!-- View Details -->
                    <a href="{% url 'tea:tea-update' tea.id %}" class="btn btn-primary btn-sm" role="button">Edit Details</a>

                    <!-- Delete Tea -->
                    <form action="{% url 'tea:tea-delete' tea.pk %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="tea_id" value="{{ tea.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <!-- Right Brewing Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'tea:gfbrew-add' tea.id %}">Add New Brew</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Brews</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Brew Type</th>
                            <th>Start Tea Sesh</th>
                            <th>Brew Temperature</th>
                            <th>Tea Quantity</th>
                            <th>Water Quantity</th>
                            <th>Steep Cycles</th>
                            <th>Edit Brew</th>
                            <th>Delete Brew</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for gf_brew in tea.gongfubrew_set.all %}
                            <tr>
                                <td>{{ gf_brew.brew_name }}</td>
                                <td>Gong Fu Brew</td>
                                <td>
                                    <form action="{% url 'tea:gfbrew-steep' gf_brew.id %}" method="get">
                                        <button type="submit" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span> Start
                                        </button>
                                    </form>
                                </td>
                                <td>{{ gf_brew.temp_C }}</td>
                                <td>{{ gf_brew.tea_qty }}</td>
                                <td>{{ gf_brew.gaiwan_size }}</td>
                                <td>{{ gf_brew.steep_num }}</td>
                                <td>
                                    <form action="{% url 'tea:gfbrew-update' gf_brew.id %}" method="get">
                                        <button type="submit" class="btn btn-warning btn-xs">
                                            <span class="glyphicon glyphicon-edit"></span> Edit
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{% url 'tea:gfbrew-delete' gf_brew.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="gongfu_brew_id" value="{{ gf_brew.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-trash"></span> Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
{% endblock %}

PycharmProjects/tea_timer/tea/templates/tea/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

PycharmProjects/tea_timer/tea/templates/tea/gongfubrew_form.html
{% extends 'tea/base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Brew Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>Add a New Brew for:</h2>
                    <h3>{{ tea }}</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="tea" value="{{ tea }}">
                        {% include 'tea/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

PycharmProjects/tea_timer/tea/templates/tea/index.html
{% extends 'tea/base.html' %}
{% block title %}{{ tea }}{% endblock %}
{% block teas_active %}active{% endblock %}

{% block body %}


    <!-- Teas -->
    <div class="row">
        {% if all_teas %}
            {% for tea in all_teas %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'tea:detail' tea.id %}">
                            <img src="{{ tea.picture.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ tea.name }}</h2>
                            <h4>{{ tea.type }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'tea:detail' tea.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Tea -->
                            <form action="{% url 'tea:tea-delete' tea.pk %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="tea_id" value="{{ tea.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'tea:tea-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Tea
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

{% endblock %}

PycharmProjects/tea_timer/tea/templates/tea/timer.html
{% extends 'tea/base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
    <!--This is the overview -->
    <div class="col-sm-4 col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <H2>Start brew for: {{ brew.brew_name }}</H2>
            </div>
            <div class="panel-body">
                <p>Timer Here</p>
                <table class="table">
                        <thead>
                            <tr>
                                <th>Steep Number</th>
                                <th>Steep Time</th>
                                <th>Completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for steep_time in steep_times %}
                            <tr>
                                <td>{{ steep_time.order }}{{ steep_time.suffix }}</td>
                                <td>{{ steep_time.time }}</td>
                                <td>
                                    <form name="{{ steep_time.order }}{{ steep_time.suffix }}_brew">
                                        <input id="start_{{ steep_time.order }}{{ steep_time.suffix }}_brew"
                                                type="button" class="btn btn-success btn-xs"
                                                onclick="setupTimer({{ steep_time.time }},
                                                        start_{{ steep_time.order }}{{ steep_time.suffix }}_brew)"
                                               value="Brew"/>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--This is the Timer -->
    <div class="col-sm-8 col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <H2>This is the Timer:</H2>
            </div>
            <div class="panel-body">
                <script>
                    setInterval("runTimer()", 1000);
                  </script>
                    <form name="steep_info">
                        <div id="start_button" hidden="true"><button type="button" class="btn btn-success btn-xs" onClick="startTimer()">
                            <span class="glyphicon glyphicon-play"></span> Start
                        </button></div>
                        <div id="pause"></div>
                    </form>
                    <div id="output"></div>
            </div>
        </div>
    </div>
{% endblock %}